spring:
  application:
    name: Application-02
  cloud:
    compatibility-verifier:
      enabled: false
  boot:
    admin:
      client:
        url: http://localhost:8080/
server:
  address: 127.0.0.1
  port: 8182

management:
  endpoints:
    web:
      exposure:
        include: '*'