spring:
  application:
    name: Microservice-Api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-01
          uri: lb://APPLICATION-01
          predicates:
            - Path=/application/hello
        - id: service-02
          uri: lb://APPLICATION-02
          predicates:
            - Path=/application/welcome
server:
  address: 127.0.0.1
  port: 4444